#!/bin/sh
# scmwd - Scan upwards in the directory tree until an SCM dir is found
# or the root directory is reached.

owd=${PWD}
#printf "Starting in %s\n" $owd
while [ 1 = 1 ]
do
	wd=${PWD}
	#printf "Looking for an SCM dir in %s\n" $wd
	if [ $wd = "/" ]; then
		printf "No .svn, .git, .bzr, or .p4 directory found above %s\n" $owd
		break
	fi
	
	if [ -d ".svn" ]; then
		printf "%s\n" ${PWD}
		break
	elif [ -d ".git" ]; then
		printf "%s\n" ${PWD}
		break
	elif [ -d ".bzr" ]; then
		printf "%s\n" ${PWD}
		break
	elif [ -d ".p4" ]; then
		printf "%s\n" ${PWD}
		break
	else
		cd ..
	fi
done
